name: Fetch and build

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run update_site_data
        npm run build
      env:
        CI: true
    - name: Commit changed files
      uses: EndBug/add-and-commit@v2.1.0 # You can change this to use a specific version
      with: # See more info about inputs below
        author_name: GitHub Action
        author_email: mail@example.com
        message: "Auto build"
        path: "./docs ./src/site_data.json"
        force: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
